library(censo2010brasil)
library(DBI)
con <- dbConnect(odbc::odbc(), driver = "SQLite3", database = path.expand('~/Downloads/Censo2010/bases_censo.sqlite'))
dbDisconnect(con)
detach("package:censo2010brasil", unload = TRUE)
