library(censo2010brasil)
library(DBI)
con <- dbConnect(odbc::odbc(), driver = "SQLite3", database = path.expand('~/Downloads/Censo2010/bases_censo.sqlite'))
dbWriteTable(con, "Basico", censo2010brasil::Basico)
dbWriteTable(con, "Domicilio01", censo2010brasil::Domicilio01)
dbWriteTable(con, "Domicilio02", censo2010brasil::Domicilio02)
dbWriteTable(con, "DomicilioRenda", censo2010brasil::DomicilioRenda)
dbWriteTable(con, "Entorno03", censo2010brasil::Entorno03)
dbWriteTable(con, "Pessoa03", censo2010brasil::Pessoa03)
dbWriteTable(con, "Responsavel02", censo2010brasil::Responsavel02)
dbDisconnect(con)
detach("package:censo2010brasil", unload = TRUE)
