#' @title DATASET_TITLE
#' @description DATASET_DESCRIPTION
#' @format A data frame with 0 rows and 241 variables:
#' \describe{
#'   \item{\code{Cod_setor}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Situacao_setor}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V202}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V203}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V204}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V205}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V206}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V207}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V208}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V209}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V210}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V211}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V212}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V213}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V214}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V215}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V216}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V217}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V218}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V219}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V220}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V221}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V222}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V223}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V224}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V225}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V226}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V227}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V228}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V229}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V230}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V231}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V232}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V233}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V234}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V235}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V236}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V237}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V238}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V239}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V240}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V241}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V242}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V243}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V244}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V245}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V246}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V247}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V248}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V249}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V250}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V251}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V252}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V253}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V254}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V255}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V256}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V257}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V258}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V259}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V260}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V261}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V262}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V263}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V264}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V265}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V266}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V267}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V268}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V269}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V270}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V271}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V272}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V273}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V274}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V275}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V276}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V277}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V278}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V279}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V280}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V281}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V282}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V283}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V284}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V285}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V286}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V287}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V288}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V289}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V290}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V291}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V292}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V293}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V294}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V295}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V296}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V297}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V298}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V299}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V300}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V301}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V302}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V303}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V304}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V305}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V306}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V307}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V308}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V309}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V310}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V311}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V312}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V313}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V314}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V315}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V316}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V317}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V318}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V319}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V320}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V321}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V322}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V323}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V324}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V325}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V326}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V327}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V328}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V329}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V330}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V331}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V332}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V333}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V334}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V335}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V336}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V337}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V338}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V339}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V340}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V341}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V342}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V343}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V344}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V345}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V346}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V347}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V348}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V349}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V350}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V351}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V352}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V353}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V354}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V355}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V356}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V357}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V358}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V359}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V360}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V361}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V362}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V363}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V364}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V365}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V366}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V367}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V368}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V369}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V370}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V371}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V372}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V373}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V374}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V375}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V376}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V377}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V378}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V379}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V380}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V381}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V382}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V383}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V384}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V385}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V386}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V387}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V388}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V389}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V390}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V391}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V392}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V393}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V394}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V395}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V396}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V397}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V398}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V399}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V400}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V401}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V402}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V403}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V404}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V405}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V406}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V407}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V408}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V409}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V410}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V411}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V412}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V413}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V414}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V415}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V416}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V417}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V418}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V419}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V420}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V421}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Setor_Precoleta}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Cod_Grandes Regiões}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_Grande_Regiao}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_UF}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_da_UF}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_meso}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_da_meso}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_micro}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_da_micro}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_RM}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_da_RM}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_municipio}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_do_municipio}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_distrito}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_do_distrito}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_subdistrito}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_do_subdistrito}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_bairro}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_do_bairro}}{character COLUMN_DESCRIPTION}
#'}
#' @source \url{http://somewhere.important.com/}
"Entorno02"
