#' @title DATASET_TITLE
#' @description DATASET_DESCRIPTION
#' @format A data frame with 0 rows and 222 variables:
#' \describe{
#'   \item{\code{Cod_setor}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Situacao_setor}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V001}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V002}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V003}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V004}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V005}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V006}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V007}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V008}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V009}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V010}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V011}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V012}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V013}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V014}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V015}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V016}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V017}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V018}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V019}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V020}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V021}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V022}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V023}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V024}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V025}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V026}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V027}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V028}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V029}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V030}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V031}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V032}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V033}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V034}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V035}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V036}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V037}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V038}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V039}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V040}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V041}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V042}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V043}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V044}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V045}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V046}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V047}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V048}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V049}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V050}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V051}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V052}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V053}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V054}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V055}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V056}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V057}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V058}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V059}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V060}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V061}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V062}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V063}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V064}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V065}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V066}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V067}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V068}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V069}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V070}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V071}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V072}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V073}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V074}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V075}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V076}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V077}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V078}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V079}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V080}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V081}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V082}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V083}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V084}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V085}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V086}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V087}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V088}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V089}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V090}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V091}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V092}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V093}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V094}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V095}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V096}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V097}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V098}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V099}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V100}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V101}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V102}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V103}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V104}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V105}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V106}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V107}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V108}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V109}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V110}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V111}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V112}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V113}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V114}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V115}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V116}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V117}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V118}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V119}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V120}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V121}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V122}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V123}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V124}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V125}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V126}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V127}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V128}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V129}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V130}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V131}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V132}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V133}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V134}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V135}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V136}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V137}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V138}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V139}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V140}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V141}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V142}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V143}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V144}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V145}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V146}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V147}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V148}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V149}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V150}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V151}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V152}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V153}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V154}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V155}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V156}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V157}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V158}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V159}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V160}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V161}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V162}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V163}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V164}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V165}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V166}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V167}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V168}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V169}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V170}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V171}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V172}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V173}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V174}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V175}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V176}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V177}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V178}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V179}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V180}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V181}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V182}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V183}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V184}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V185}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V186}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V187}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V188}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V189}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V190}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V191}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V192}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V193}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V194}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V195}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V196}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V197}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V198}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V199}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V200}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V201}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Setor_Precoleta}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Cod_Grandes Regiões}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_Grande_Regiao}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_UF}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_da_UF}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_meso}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_da_meso}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_micro}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_da_micro}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_RM}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_da_RM}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_municipio}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_do_municipio}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_distrito}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_do_distrito}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_subdistrito}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_do_subdistrito}}{character COLUMN_DESCRIPTION}
#'   \item{\code{Cod_bairro}}{double COLUMN_DESCRIPTION}
#'   \item{\code{Nome_do_bairro}}{character COLUMN_DESCRIPTION}
#'}
#' @source \url{ftp://ftp.ibge.gov.br/Censos/Censo_Demografico_2010/Resultados_do_Universo/Agregados_por_Setores_Censitarios/}
"Entorno01"
