#' @title DATASET_TITLE
#' @description DATASET_DESCRIPTION
#' @format A data frame with 310120 rows and 202 variables:
#' \describe{
#'   \item{\code{Cod_setor}}{character COLUMN_DESCRIPTION}
#'   \item{\code{V422}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V423}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V424}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V425}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V426}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V427}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V428}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V429}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V430}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V431}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V432}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V433}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V434}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V435}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V436}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V437}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V438}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V439}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V440}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V441}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V442}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V443}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V444}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V445}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V446}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V447}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V448}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V449}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V450}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V451}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V452}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V453}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V454}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V455}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V456}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V457}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V458}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V459}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V460}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V461}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V462}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V463}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V464}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V465}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V466}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V467}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V468}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V469}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V470}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V471}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V472}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V473}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V474}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V475}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V476}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V477}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V478}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V479}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V480}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V481}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V482}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V483}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V484}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V485}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V486}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V487}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V488}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V489}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V490}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V491}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V492}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V493}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V494}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V495}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V496}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V497}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V498}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V499}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V500}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V501}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V502}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V503}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V504}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V505}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V506}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V507}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V508}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V509}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V510}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V511}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V512}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V513}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V514}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V515}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V516}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V517}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V518}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V519}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V520}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V521}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V522}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V523}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V524}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V525}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V526}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V527}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V528}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V529}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V530}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V531}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V532}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V533}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V534}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V535}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V536}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V537}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V538}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V539}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V540}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V541}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V542}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V543}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V544}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V545}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V546}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V547}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V548}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V549}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V550}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V551}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V552}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V553}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V554}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V555}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V556}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V557}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V558}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V559}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V560}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V561}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V562}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V563}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V564}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V565}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V566}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V567}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V568}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V569}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V570}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V571}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V572}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V573}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V574}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V575}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V576}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V577}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V578}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V579}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V580}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V581}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V582}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V583}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V584}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V585}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V586}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V587}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V588}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V589}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V590}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V591}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V592}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V593}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V594}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V595}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V596}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V597}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V598}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V599}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V600}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V601}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V602}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V603}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V604}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V605}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V606}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V607}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V608}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V609}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V610}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V611}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V612}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V613}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V614}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V615}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V616}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V617}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V618}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V619}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V620}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V621}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V622}}{double COLUMN_DESCRIPTION}
#'}
#' @source \url{http://somewhere.important.com/}
"Entorno03"
