#' @title DATASET_TITLE
#' @description DATASET_DESCRIPTION
#' @format A data frame with 310114 rows and 221 variables:
#' \describe{
#'   \item{\code{Cod_setor}}{character COLUMN_DESCRIPTION}
#'   \item{\code{V843}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V844}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V845}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V846}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V847}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V848}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V849}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V850}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V851}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V852}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V853}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V854}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V855}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V856}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V857}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V858}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V859}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V860}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V861}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V862}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V863}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V864}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V865}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V866}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V867}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V868}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V869}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V870}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V871}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V872}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V873}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V874}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V875}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V876}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V877}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V878}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V879}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V880}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V881}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V882}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V883}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V884}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V885}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V886}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V887}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V888}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V889}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V890}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V891}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V892}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V893}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V894}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V895}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V896}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V897}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V898}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V899}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V900}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V901}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V902}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V903}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V904}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V905}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V906}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V907}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V908}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V909}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V910}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V911}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V912}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V913}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V914}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V915}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V916}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V917}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V918}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V919}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V920}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V921}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V922}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V923}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V924}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V925}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V926}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V927}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V928}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V929}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V930}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V931}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V932}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V933}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V934}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V935}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V936}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V937}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V938}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V939}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V940}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V941}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V942}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V943}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V944}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V945}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V946}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V947}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V948}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V949}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V950}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V951}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V952}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V953}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V954}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V955}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V956}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V957}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V958}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V959}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V960}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V961}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V962}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V963}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V964}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V965}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V966}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V967}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V968}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V969}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V970}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V971}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V972}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V973}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V974}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V975}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V976}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V977}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V978}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V979}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V980}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V981}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V982}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V983}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V984}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V985}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V986}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V987}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V988}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V989}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V990}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V991}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V992}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V993}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V994}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V995}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V996}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V997}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V998}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V999}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1000}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1001}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1002}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1003}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1004}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1005}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1006}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1007}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1008}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1009}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1010}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1011}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1012}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1013}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1014}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1015}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1016}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1017}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1018}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1019}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1020}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1021}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1022}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1023}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1024}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1025}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1026}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1027}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1028}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1029}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1030}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1031}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1032}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1033}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1034}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1035}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1036}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1037}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1038}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1039}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1040}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1041}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1042}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1043}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1044}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1045}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1046}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1047}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1048}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1049}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1050}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1051}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1052}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1053}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1054}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1055}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1056}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1057}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1058}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1059}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1060}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1061}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V1062}}{double COLUMN_DESCRIPTION} 
#'}
#' @source \url{http://somewhere.important.com/}
"Entorno05"
