#' @title DATASET_TITLE
#' @description DATASET_DESCRIPTION
#' @format A data frame with 310120 rows and 135 variables:
#' \describe{
#'   \item{\code{Cod_setor}}{character COLUMN_DESCRIPTION}
#'   \item{\code{V001}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V002}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V003}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V004}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V005}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V006}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V007}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V008}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V009}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V010}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V011}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V012}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V013}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V014}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V015}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V016}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V017}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V018}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V019}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V020}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V021}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V022}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V023}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V024}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V025}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V026}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V027}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V028}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V029}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V030}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V031}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V032}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V033}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V034}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V035}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V036}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V037}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V038}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V039}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V040}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V041}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V042}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V043}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V044}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V045}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V046}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V047}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V048}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V049}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V050}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V051}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V052}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V053}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V054}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V055}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V056}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V057}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V058}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V059}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V060}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V061}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V062}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V063}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V064}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V065}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V066}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V067}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V068}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V069}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V070}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V071}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V072}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V073}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V074}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V075}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V076}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V077}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V078}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V079}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V080}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V081}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V082}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V083}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V084}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V085}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V086}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V087}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V088}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V089}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V090}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V091}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V092}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V093}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V094}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V095}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V096}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V097}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V098}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V099}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V100}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V101}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V102}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V103}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V104}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V105}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V106}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V107}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V108}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V109}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V110}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V111}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V112}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V113}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V114}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V115}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V116}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V117}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V118}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V119}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V120}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V121}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V122}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V123}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V124}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V125}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V126}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V127}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V128}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V129}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V130}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V131}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V132}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V133}}{double COLUMN_DESCRIPTION}
#'   \item{\code{V134}}{double COLUMN_DESCRIPTION}
#'}
#' @source \url{http://somewhere.important.com/}
"Pessoa11"
